services:

  # Data base
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app_net

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - app_net

  # S3 storage
  minio-setup:
    container_name: minio_setup
    build:
      context: .
      dockerfile: docker/minio_mc/Dockerfile
    restart: "no"
    depends_on:
      - minio
      - sync-worker
    env_file:
      - .env
    networks:
      - app_net

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app_net

  sync-worker:
    container_name: sync_worker
    build:
      context: .
      dockerfile: docker/sync_worker/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    env_file:
      - .env
    networks:
      - app_net

  # tg bot
  telegram_bot:
    container_name: telegram_bot
    build:
      context: .
      dockerfile: docker/telegram_bot/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - app_net

  # Proxy
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/prod/logs:/var/log/nginx/
      - ./docker/nginx/prod/ssl:/etc/nginx/ssl:ro
    depends_on:
      - minio
      - adminer
    networks:
      - app_net

volumes:
  minio-storage:
  postgres_data:

networks:
  app_net:
