events {}

http {
    server {
        listen 80;

        # use for S3 API + redirect browsers to 9001 UI endpoint
        location /minio/ {
            proxy_pass http://minio:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
